version: '{build}'
image: Visual Studio 2017

environment:
  LOG_TRACE: 1
  PATH: node_modules/.bin;%PATH%

install:
  - npm install
  - npm install android-build-tools -g
  - ps: Invoke-WebRequest https://www.nuget.org/api/v2/package/mesa3d-x64/18.3.4 -OutFile mesa.zip
  - ps: Expand-Archive mesa.zip mesa

build_script:
  - npm pack --silent
  # Run Android build using Bash so we can kill Java to avoid that PowerShell
  # hangs, and still return the exit code from Uno.
  - bash -c "uno build android Tests/ManualTests/ManualTestingApp/ManualTestingApp.unoproj; exitcode=$?; taskkill //F //IM java.exe //T; exit $exitcode"
  # Build for Windows
  - uno build native Tests/ManualTests/ManualTestingApp/ManualTestingApp.unoproj

artifacts:
  - path: '*.tgz'

before_test:
  - ps: |
      Get-ChildItem -Path Source -Recurse -Include *Test.unoproj | Select-Object -ExpandProperty DirectoryName | Foreach-Object {
        $buildDir = Join-Path $_ build\Test\DotNet
        New-Item -Force -ItemType directory -Path $buildDir | Out-Null
        Copy-Item -Path mesa\opengl32.dll -Destination (Join-Path $buildDir opengl32.dll)
      }

test_script:
  - npm run test
